---
driver:
  name: vagrant
provisioner:
  name: chef_zero
platforms:
- name: centos-6.4
  driver_plugin: vagrant
  provisioner:
    require_chef_omnibus: true
  driver_config:
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
suites:
- name: default
  run_list:
  - recipe[scponly_test::default]
  attributes:
