name             'scponly'
maintainer       'Criteo'
maintainer_email 'sre-core-infra@criteo.com'
license          'Apache-2.0'
description      'Installs/Configures scponly'
long_description 'Scponly Cookbook
Install `scponly` package and configure `scponly` shells ([Scponly wiki](https://github.com/scponly/scponly/wiki))
'
issues_url       'https://github.com/criteo-cookbooks/scponly'
source_url       'https://github.com/criteo-cookbooks/scponly'
version          '1.0.0'
supports         'centos'
supports         'redhat'
depends          'yum-epel'
chef_version     '> 12.5.0'
