name             'scponly'
maintainer       'Criteo'
maintainer_email 'j.mauro@criteo.com'
license          'Apache 2.0'
description      'Installs/Configures scponly'
issues_url       'https://github.com/criteo-cookbooks/scponly/issues'
source_url       'https://github.com/criteo-cookbooks/scponly'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.1'
depends          'yum-epel'
